# docker-compose.yml
version: "3.8"

services:
  emotion-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./app:/app/app
    restart: unless-stopped
